export const questions = [
  {
    id: 1,
    section: "말초신경계",
    prompt: "해부학적 구조에 따라 말초신경계는 ____과 ____으로 구분된다.",
    answers: ["뇌신경", "척수신경"],
    type: "multi",
  },
  {
    id: 2,
    section: "말초신경계",
    prompt: "감각기관에서 받은 자극을 중추신경계로 전달하는 말초신경은 ____ 신경이다.",
    answers: ["구심성", "감각"],
    type: "any",
  },
  {
    id: 3,
    section: "말초신경계",
    prompt: "중추신경계의 명령을 반응기로 전달하는 말초신경은 ____ 신경이다.",
    answers: ["원심성", "운동"],
    type: "any",
  },
  {
    id: 4,
    section: "말초신경계",
    prompt: "원심성 신경은 ____ 신경계와 ____ 신경계로 나뉜다.",
    answers: ["체성", "자율"],
    type: "multi",
  },
  {
    id: 5,
    section: "말초신경계",
    prompt: "체성신경계의 반응기는 주로 ____이다.",
    answers: ["골격근"],
    type: "single",
  },
  {
    id: 6,
    section: "말초신경계",
    prompt: "체성신경계에서는 중추신경계에서 반응기까지 시냅스 없이 ____개의 뉴런으로 연결된다.",
    answers: ["1개", "1", "하나"],
    type: "any",
  },
  {
    id: 7,
    section: "말초신경계",
    prompt: "자율신경계에서 중추신경계와 반응기 사이에 존재하는 구조는 ____이다.",
    answers: ["신경절"],
    type: "single",
  },
  {
    id: 8,
    section: "말초신경계",
    prompt: "자율신경계는 ____과 ____으로 구성된다.",
    answers: ["교감신경", "부교감신경"],
    type: "multi",
  },
  {
    id: 9,
    section: "말초신경계",
    prompt: "교감신경에서 더 긴 쪽은 신경절 ____ 뉴런이다.",
    answers: ["이후"],
    type: "single",
  },
  {
    id: 10,
    section: "말초신경계",
    prompt: "부교감신경에서 더 긴 쪽은 신경절 ____ 뉴런이다.",
    answers: ["이전"],
    type: "single",
  },
  {
    id: 11,
    section: "말초신경계",
    prompt: "교감신경의 신경절 이전 뉴런 말단에서 분비되는 신경전달물질은 ____이다.",
    answers: ["아세틸콜린"],
    type: "single",
  },
  {
    id: 12,
    section: "말초신경계",
    prompt: "교감신경의 신경절 이후 뉴런 말단에서 주로 분비되는 신경전달물질은 ____이다.",
    answers: ["노르에피네프린", "노레피네프린", "노르아드레날린", "norepinephrine", "noradrenaline"],
    type: "any",
  },
  {
    id: 13,
    section: "말초신경계",
    prompt: "부교감신경은 신경절 이전과 이후 뉴런 말단에서 모두 ____을 분비한다.",
    answers: ["아세틸콜린"],
    type: "single",
  },
  {
    id: 14,
    section: "말초신경계",
    prompt: "자율신경계는 각종 ____ 기관, 혈관, 내분비샘에 주로 분포한다.",
    answers: ["내장"],
    type: "single",
  },
  {
    id: 15,
    section: "척수",
    prompt: "척수는 ____에 이어져 있으며, 척추에 싸여 보호된다.",
    answers: ["숨골", "연수"],
    type: "any",
  },
  {
    id: 16,
    section: "척수",
    prompt: "척수에서 바깥쪽은 ____질, 안쪽은 ____질이다.",
    answers: ["백색", "회색"],
    type: "multi",
  },
  {
    id: 17,
    section: "척수",
    prompt: "척수에서는 좌우 한 쌍씩 총 ____쌍의 신경 다발이 나온다.",
    answers: ["31쌍", "31", "서른한쌍", "서른한"],
    type: "any",
  },
  {
    id: 18,
    section: "척수",
    prompt: "척수의 배 쪽으로 나와 전근을 이루는 것은 ____성 신경 다발이다.",
    answers: ["원심성", "운동"],
    type: "any",
  },
  {
    id: 19,
    section: "척수",
    prompt: "척수의 등 쪽으로 나와 후근을 이루는 것은 ____성 신경 다발이다.",
    answers: ["구심성", "감각"],
    type: "any",
  },
  {
    id: 20,
    section: "척수",
    prompt: "척수는 감각기관에서 받아들인 정보를 ____로 전달하고, 뇌에서 내린 명령을 ____로 전달한다.",
    answers: ["뇌", "반응기"],
    type: "multi",
  },
  {
    id: 21,
    section: "척수",
    prompt: "척수는 여러 가지 반사 행동의 ____이다.",
    answers: ["중추"],
    type: "single",
  },
  {
    id: 22,
    section: "척수",
    prompt: "전근이 손상되면 신체 특정 부위의 ____ 기능에 이상이 생긴다.",
    answers: ["운동"],
    type: "single",
  },
  {
    id: 23,
    section: "척수",
    prompt: "후근이 손상되면 신체 특정 부위의 ____ 기능에 이상이 생긴다.",
    answers: ["감각"],
    type: "single",
  },
  {
    id: 24,
    section: "척수",
    prompt: "척수가 손상되면 손상된 부위 아래의 ____과 ____이 마비된다.",
    answers: ["감각", "운동"],
    type: "multi",
  },
  {
    id: 25,
    section: "척수",
    prompt: "머리 아래 부분의 감각기관과 반응기를 오가는 대부분의 신호는 ____를 통과한다.",
    answers: ["척수"],
    type: "single",
  },
  {
    id: 26,
    section: "척수",
    prompt: "얼굴 부위 감각기관에서 받아들인 감각 정보는 보통 ____를 거치지 않고 대뇌로 전달된다.",
    answers: ["척수"],
    type: "single",
  },
  {
    id: 27,
    section: "의식적인 반응과 무조건반사",
    prompt: "의식적인 반응과 무조건반사는 반응 과정에 ____의 관여 여부에 따라 구분된다.",
    answers: ["대뇌"],
    type: "single",
  },
  {
    id: 28,
    section: "의식적인 반응과 무조건반사",
    prompt: "의식적인 반응의 경로에서 감각신경 다음에 오는 중추신경계는 ____이다.",
    answers: ["대뇌"],
    type: "single",
  },
  {
    id: 29,
    section: "의식적인 반응과 무조건반사",
    prompt: "무조건반사에서는 신호가 ____에 전달되기 전에 빠르게 반응이 일어난다.",
    answers: ["대뇌"],
    type: "single",
  },
  {
    id: 30,
    section: "의식적인 반응과 무조건반사",
    prompt: "무조건반사의 중추가 될 수 있는 곳은 ____, ____, ____이다.",
    answers: ["중간뇌", "숨골", "척수"],
    type: "multi",
  },
  {
    id: 31,
    section: "의식적인 반응과 무조건반사",
    prompt: "무릎반사의 중추는 ____이다.",
    answers: ["척수"],
    type: "single",
  },
  {
    id: 32,
    section: "의식적인 반응과 무조건반사",
    prompt: "침 분비 반사의 중추는 ____이다.",
    answers: ["숨골"],
    type: "single",
  },
  {
    id: 33,
    section: "의식적인 반응과 무조건반사",
    prompt: "동공반사의 중추는 ____이다.",
    answers: ["중간뇌"],
    type: "single",
  },
  {
    id: 34,
    section: "의식적인 반응과 무조건반사",
    prompt: "척수 반사 경로에서 감각신경은 ____을 통해 척수로 들어가고, 운동신경은 ____을 통해 나간다.",
    answers: ["후근", "전근"],
    type: "multi",
  },
  {
    id: 35,
    section: "의식적인 반응과 무조건반사",
    prompt: "의식적인 반응의 신호 전달에서 대뇌와 척수를 연결하는 신경은 대부분 ____에서 좌우가 교차한다.",
    answers: ["숨골"],
    type: "single",
  },
  {
    id: 36,
    section: "의식적인 반응과 무조건반사",
    prompt: "오른쪽 피부의 감각 자극에 대한 의식적인 반응에서는 정보가 먼저 ____쪽 대뇌 반구로 전달된다.",
    answers: ["왼쪽", "좌측", "왼"],
    type: "any",
  },
  {
    id: 37,
    section: "교감신경과 부교감신경",
    prompt: "같은 내장 기관에 대해 서로 반대 효과를 나타내며 기능을 조절하는 작용을 ____작용이라 한다.",
    answers: ["길항"],
    type: "single",
  },
  {
    id: 38,
    section: "교감신경과 부교감신경",
    prompt: "심장박동에는 ____신경이 촉진적으로, ____신경이 억제적으로 작용한다.",
    answers: ["교감", "부교감"],
    type: "multi",
  },
  {
    id: 39,
    section: "교감신경과 부교감신경",
    prompt: "소화관 운동과 소화액 분비를 촉진하는 쪽은 ____신경이다.",
    answers: ["부교감"],
    type: "single",
  },
  {
    id: 40,
    section: "교감신경과 부교감신경",
    prompt: "교감신경이 우세할 때 동공은 ____, 침 분비는 ____, 숨관가지는 ____한다.",
    answers: ["확대", "억제", "확장"],
    type: "multi",
  },
  {
    id: 41,
    section: "교감신경과 부교감신경",
    prompt: "부교감신경이 우세할 때 동공은 ____, 방광은 ____, 심장박동은 ____된다.",
    answers: ["축소", "수축", "억제"],
    type: "multi",
  },
  {
    id: 42,
    section: "교감신경과 부교감신경",
    prompt: "교감신경은 척수의 ____ 부분에서, 부교감신경은 중간뇌·숨골·척수의 ____ 부분에서 나온다.",
    answers: ["중간", "꼬리"],
    type: "multi",
  },
];